- name: Add Mongodb Repository
  yum_repository:
    name: MongoDB Repository
    description: MongoDB Repository
    baseurl: https://repo.mongodb.org/yum/redhat/$releasever/mongodb-org/4.2/x86_64/
    enabled: yes
    gpgcheck: yes
    gpgkey: https://www.mongodb.org/static/pgp/server-4.2.asc
    file: mongodb

- name: Install Mongodb
  yum:
    name: mongodb-org
    state: latest

- name: Start Mongodb service
  systemd:
    name: mongod
    enabled: yes
    state: started
