- name: Add Mongodb Repository
  yum_repository:
    name: MongoDB
    description: MongoDB Repository
    baseurl: https://repo.mongodb.org/yum/redhat/$releasever/mongodb-org/4.2/x86_64/
    enabled: yes
    gpgcheck: yes
    gpgkey: https://www.mongodb.org/static/pgp/server-4.2.asc
    file: mongodb

- name: Install Mongodb
  yum:
    name: mongodb-org
    state: present

- name: Update Mongodb Listen Address
  ansible.builtin.replace:
    path: /etc/mongod.conf
    regexp: '127.0.0.1'
    replace: '0.0.0.0'
  notify:
    - Restart Mongodb
#handlers will run at the end of play

- name: Start Mongodb service
  systemd:
    name: mongod
    enabled: yes
    state: restarted

- name: Download Package
  include_role:
    name: common
    tasks_from: download-from-github
  vars:
    APP_DIR: /tmp/mongodb-main
    EXTRACT_DIR: /tmp

- name: Load Schema
  community.mongodb.mongodb_shell:
    file: "/tmp/mongodb-main/users.js"
    idempotent: yes

