- name: Demo on Variables
  hosts: all
  vars:
    URL: play.example.com
  tasks:
  - name: Print Variable
    debug:
      msg: URL = {{URL}}
  - name: Print Variable
    vars:
      URL: task.exapmle.com
    debug:
      msg:  URL = {{URL}}
- name: Demo on Variabkes from File
  hosts: all
  vars_files:
    - example-vars.yml
  tasks:
    - name: Print Variable
      debug:
        msg: URL = {{URL}}