- name: Demo on Tags
  hosts: localhost
  tags:
    - AZURE
  tasks:
    - name: Print AWS
      debug:
        msg: AWS
      tags:
        - AWS
    - name: Print AZURE
      debug:
        msg: AZURE