- name: Demo on Conditions
  hosts: localhost
  vars:
    IS_RUN: true
  tasks:
    - name: Run Based on User Input
      debug:
        msg: Hello World
      when: IS_RUN

- name: Demo on Conditions using Loops
  hosts: localhost
  shell: echo {{item}}
  loop: [ 1, 3, 5, 7, 9 ]
  when: item > 3