- name: Demo on Conditions
  hosts: localhost
  vars:
    IS_RUN: true
  tasks:
    - name: Run Based on User Input
      debug:
        msg: Hello World
      when: IS_RUN

- name: Demo on Conditions using Loops
  hosts: localhost
  tasks:
    - name: Run with items greater than 5
      ansible.builtin.command: echo {{ item }}
      loop: [ 0, 2, 4, 6, 8, 10 ]
      when: item > 5