- name: Setup roboshop project --frontend component
  hosts: FRONTEND
  become: yes
  tags:
    - frontend
  roles:
    - name: Load Frontend role
      role: frontend

- name: Setup roboshop project --frontend component
  hosts: MONGODB
  become: yes
  tags:
    - mongodb
  roles:
    - name: Load Mongodb role
      role: mongodb

- name: Setup roboshop project --catalogue component
  hosts: CATALOGUE
  become: yes
  tags:
    - catalogue
  roles:
    - name: Load catalogue role
      role: catalogue

- name: Setup roboshop project --redis component
  hosts: REDIS
  become: yes
  tags:
    - redis
  roles:
    - name: Load catalogue role
      role: redis