- name: Clean Known Hosts
  hosts: localhost
  tasks:
    - name: Clean Known Hosts
      file:
        path: ~/.ssh/known_hosts
        state: absent

- name: Setup roboshop project --frontend component
  hosts: FRONTEND
  become: yes
  tags:
    - frontend
  roles:
    - name: Load Frontend role
      role: frontend

- name: Setup roboshop project --frontend component
  hosts: MONGODB
  become: yes
  tags:
    - mongodb
  roles:
    - name: Load Mongodb role
      role: mongodb

- name: Setup roboshop project --catalogue component
  hosts: CATALOGUE
  become: yes
  tags:
    - catalogue
  roles:
    - name: Load catalogue role
      role: catalogue

- name: Setup roboshop project --redis component
  hosts: REDIS
  become: yes
  tags:
    - redis
  roles:
    - name: Load redis role
      role: redis

- name: Setup roboshop project --user component
  hosts: USER
  become: yes
  tags:
    - user
  roles:
    - name: Load user role
      role: user

- name: Setup roboshop project --cart component
  hosts: CART
  become: yes
  tags:
    - cart
  roles:
    - name: Load cart role
      role: cart

- name: Setup roboshop project --mysql component
  hosts: MYSQL
  become: yes
  tags:
    - mysql
  roles:
    - name: Load mysql role
      role: mysql

- name: Setup roboshop project --shipping component
  hosts: SHIPPING
  become: yes
  tags:
    - shipping
  roles:
    - name: Load shipping role
      role: shipping

- name: Setup roboshop project --rabbitmq component
  hosts: RABBITMQ
  become: yes
  tags:
    - rabbitmq
  roles:
    - name: Load rabbitmq role
      role: rabbitmq

- name: Setup roboshop project --payment component
  hosts: PAYMENT
  become: yes
  tags:
    - payment
  roles:
    - name: Load payment role
      role: payment