- name: Add MYSQL repository
  yum_repository:
    name: MySQL
    description: MySQL repo
    baseurl: http://repo.mysql.com/yum/mysql-5.7-community/el/7/$basearch/
    enabled: yes
    gpgcheck: no
    file: mysql

- name: Remove Mariadb Libraries
  yum:
    name: mariadb-libs
    state: absent

- name: Install MySQL Server
  yum:
    name:
     - mysql-community-server
     - MySQL-python
    state: present

- name: Start MySQL Service
  systemd:
    state: started
    name: mysqld
    enabled: yes

- name: Grabbing Default password
  shell: grep "A temporary password" /var/log/mysqld.log | awk '{print $NF}'
  register: MYSQL_DEFAULT_PASSWORD

- name: Debug
  debug:
    msg: "{{MYSQL_DEFAULT_PASSWORD}}"

- name: Set MySQL root Password
  mysql_user:
    login_host: 'localhost'
    login_user: 'root'
    login_password: "{{MYSQL_DEFAULT_PASSWORD.stdout}}"
    name: 'root'
    password: 'Roboshop@1'
    state: present